<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>E-Mailing</title>
<link rel="stylesheet" href="<?php echo realpath; ?>/css/style2.css" type="text/css" media="screen" charset="utf-8"/>
<script src="<?php echo realpath;?>/js/jquery-1.7.2.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo realpath; ?>/js/script2.js"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo realpath;?>/js/jquery-ui-1.8.20.custom.min.js"></script>
</head>
<body>
<div id='container'>
	<div id="mainMenuContainer">
		<div id="mainMenu">
			<p>main menu</p>
				<input class="button" type="button" value="campaign"/>
				<input class="button" type="button" value="deployment"/>
		</div>
		<div id="mainMenuLogo">
			<img src="<?php echo realpath; ?>img/mainMenu.jpg" alt="mainmenu"/>
		</div>
	</div>
	<div id="mainMenuTabNav">
		<div id="campaign">
			<div id="creatives">
			<form id="newCreative" method="post" action='<?php echo realpath."campagin/inserting" ?>'>
				<table>
					<tr>
						<td><label>Campaign Name</label></td>
						<td><input id="campaignName" name="campaignName" type="text" /></td>
					</tr>			
					<tr class="options">
						<td><label>Advertiser</label></td>
						<td><select id="advertiser" name="advertiser">
						<option>Choose An Advertiser</option>
						<?php
						if(isset($this->data))
							foreach($this->data as $value)
								if($value["type"] == "Advertiser")
									echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
							?>							
							</select></td>
						</tr>	
						<tr class="options">
							<td><label>Ad Network</label></td>
							<td><select id="network" name="network">
								<option>Choose A Network</option>
								<?php
									if(isset($this->data))
										foreach($this->data as $value)
											if($value["type"] == "Ad Network")
												echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
								?>
						</select></td>
					 </tr>		
					<tr class="options">
						<td><label>Offers</label></td>
						<td><select id="offers" name="offers">
							<option>Choose A Offer</option>
						<?php
							if(isset($this->data))
								foreach($this->data as $value)
									if($value["type"] == "Offers")
										echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
						?>
						</select></td>
					</tr>
		
					<tr class="options">
						<td><label>Domains</label></td>
						<td><select id="domains"  name="domains">
								<option>Choose A Domain</option>
								<?php
									if(isset($this->data))
										foreach($this->data as $value)
											if($value["type"] == "Domains")
												echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
								?>
							</select></td>
					</tr>		
					<tr class="options">
					<td><label>Cluster</label></td>
					<td><select id="cluster" name="cluster">
						<option>Choose A Cluster</option>
							<?php
									if(isset($this->data))
										foreach($this->data as $value)
											if($value["type"] == "Cluster")
												echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
								?>
					</select></td>
				</tr>	
				<tr>
					<td></td>
					<td><input id="createCreative" type="submit" value="Create Creative"/></td>
				</tr>
			</form>
		</table>
	</div>
<div id="listCreatives">
	<ul>
		<?php
			foreach($this->camp as $value)
				echo "<li><a href='".realpath."campagin/updating?cid=".$value["id"]."' style='color:blue' >".$value["cluster"]."---".$value["id"]." ".$value["campaignName"]." ".$value['date'].' '.$value['domains']."</a></li>";
		?>
	</ul>
</div>	
</div>
<div id="deployment" class="current">
    <ul id="tabNav">
	<li><a href="#domainManagement">Domain Management</a></li>
	<li ><a href="#templateManagement">Template Management</a></li>
 <li><a href="#test_send">Test & Send</a></li>
    </ul>
  <div id="domainManagement">
    <div id="domain">
    <fieldset>
    	<legend>Domains</legend>
 <table>
    	<tr>
    		<td>	
			    <ul id="domainAvaliable" class="domainConnect sortable">
			    	<li id="a">a</li>
			    	<li id="b">b</li>
			    	<li id="c">c</li>
			    </ul>
			 </td>
			 <td>   
			    <ul id="domainSelected" class="domainConnect sortable selection">
			    	<li class="ui-state-highlight" id="d">d</li>
			    	<li class="ui-state-highlight" id="e">e</li>
			    	<li class="ui-state-highlight" id="f">f</li>
			    </ul>
		</tr>
	    	<td></td><td><input id="domainSave" class="saveSelection" type="button" value="Save Domain"/></td>
	    </tr>
 	</table>
    	
    </fieldset>
    </div>
    
   <div id="ip">
 	<fieldset>
 		<legend>IPs</legend>
 		 	 <table>
    		<tr><td><ul id="IpAvaliable" class="IpConnect sortable">
			    	<li id="a">a</li>
			    	<li id="b">b</li>
			    	<li id="c">c</li>
			</ul></td>
		
			 <td><ul id="IpSelected" class="IpConnect sortable selection">
			    	<li class="ui-state-highlight" id="d">d</li>
			    	<li class="ui-state-highlight" id="e">e</li>
			    	<li class="ui-state-highlight" id="f">f</li>
			    </ul></tr>
			<td></td>
		<td><input id="domainSave" class="saveSelection" type="button" value="Save IP"/></td></tr>
	    
 	</table>
 		
 	</fieldset>
 	</div>


  </div>
	
    <div id="templateManagement">
		<form name="templateForm" method="post">
        <table>
        	<tr>
            	<td>
                	<lable>Creative:</lable>
					<select>
	                    <option value="">Select Creative Id...</option>
                    	<option value="1234">1234</option>
                       	<option value="2234">2234</option>
                    </select>
                </td>
                
                <td>   
                    <lable>Template:</lable>
					<select>
	                    <option value="">Select a template..</option>
                    	<option value="1234-1">1234-1</option>
                       	<option value="1234-2">2234-2</option>
                    </select>
                </td>
                
                <td>
                	<label>New Template Name:</label>
                    <input type="text"/>
                    <input type="button" id="saveTemplate" value="Save Template"/>
                </td>
            </tr>
			
            <tr>
            	<td><input class="clear" type="text" value="Enter email for Testing"/></td>
                <td><input type="button" value="Send Single Test"/></td>
            </tr>
<tr>
<td colspan="3">


             	<textarea>
From: Credit-Scores<creditscores@[fromdomain]>
Subject: [seednum] Your up-to-date credit scores are available online. Inquire inside
MIME-Version: 1.0
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<title>FreeCreditClick </title>
<body bgcolor="#ffffff" text="#000000">
<center>
	
<p style="font-size: 10pt; font-family: Verdana, Arial, Helvitica,
      Tahoma, sans-serif;text-align:center">
<a href="http://www.[redirdomain]/i-[rand6]?token=278757-2802-94322-[uid]">
        <img src="http://www.[redirdomain]/i-[rand1]?token=278757-92840577-94322-[uid]" alt="Your up-to-date credit scores are available online. Inquire inside" /></a>
</p>
                
                	</textarea>
                 </td>
</tr>
        </table>
	</form>
    </div>
    
<div id="test_send">
      
						
								<select>
									<option value="2546">2546</option>
								</select>
							</td></tr>
									<fieldset>
										<legend>Template Testing</legend>
						<table>
							<tr colspan="1" rowspan="2">
							
								<td>
										<label>Avaliable Templates</label>
									<ul id="templateAvaliable" class="sortable templateConnect">
									<li class="ui-state-default" id="1">Template1</li>
									<li class="ui-state-default" id="2">Template2</li>
									<li class="ui-state-default" id="3">Template3</li>
                 	<li class="ui-state-default" id="4">Template4</li>
									<li class="ui-state-default" id="5">Template5</li>
									<li class="ui-state-default" id="6">Template6</li>
									</ul>		
								</td>
								
								<td>
									<label>Selected Templates</label>
									<ul id="templateSelected" class="sortable templateConnect">
											<li class="ui-state-default" id="7">Template7</li>
									</ul>
								</td>
							
							<td>								
									<fieldset>
										<legend>Volume Test</legend>
											<form id="testVolume">
												<table>
														<?php	for($i=1;$i<=5;$i++){?>
																<tr><td>
																<input type="text" class="testAccounts clear" name="account<?php echo $i;?>" class="clear" value="enter 1st seed email here" />
																</td>
																<td> x </td>
																<td>
																<input type="text" class="clear" name="volume<?php echo $i;?>" value="Volume" />
																</td></tr>
														<?php } ?> 
																<tr>
																	<td colspan="2"></td>
																	<td>
																		<input type="submit" value="Send Volume Test" name="templateVolumeTest">
																	</td>
																</tr>
																
												</table>
											</form>			
									</fieldset>
								</td>
								</tr>
								
							<tr><td></td><td></td>
							<td>
								
								<fieldset>
									<legend>Send</legend>
										<form id="sendList" action="<?php echo APPLICATION_PATH; ?>/others/email.php" method="POST">
										<table>
											<tr>
												<td>
												<select name="productionList">
													<option value="yahoo">Yahoo-2-12-(563215325)</option>
													<option value="Gmail">Gmail-2-12-(563215325)</option>
													<option value="AOL">Aol-2-12-(563215325)</option>
												</select>
												</td>
												<td><input name="seedInterval" type="input" class="clear" value="seed Interval"/>
												<td><input name="seedAccount" type="input" class="clear" value="Seed Account"/>
												</td>
												<tr>
																	<td colspan="2"></td>
																	<td>
																		<input type="submit" value="Send Volume Test" name="templateVolumeTest" />
																	</td>
																</tr>
											</tr>	
										</table>
									</form>	
								</fieldset>
								
							</td>									
							</tr>
							<tr><td colspan="2"></td>
							<td>
								
								<fieldset>
									<legend>Bulk Setup</legend>
								<form id="sendBulk" action="<?php echo realpath ?>campagin/send" method="POST">
									<table>
										<tr>
											<td><input class="clear" type="text" name="bulkCampaignId" value="Campaign ID"/></td>
											<td><input type="submit" name="setBulk" value="Set Bulk"/></td>
										</tr>
									</table>
							
								</fieldset>
							</td></tr>	
							<form>
						</table>
					</fieldset>
						
									
			  	
        	
</div>

</div><!--end of deployment-->    
</div><!--end of main menu tab nav-->
</div>
</body>
</html>
