<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>E-Mailing</title>
	<link rel="stylesheet" href="<?php echo realpath; ?>css/style.css" type="text/css" media="screen" charset="utf-8"/>
	<script src="<?php echo realpath; ?>js/jquery-1.4.min.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" src="<?php echo realpath; ?>js/script.js"></script>	
	<script language="JavaScript" type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
</head>
<body>
<div id='container'>
	<div id="campaign">
		<div id="creatives">
			<form id="newCreative" method="post" action='<?php echo realpath."campagin/inserting" ?>'>
				<table>
					<tr>
						<td><label>Campaign Name</label></td>
						<td><input id="campaignName" name="campaignName" type="text" /></td>
					</tr>			
					<tr class="options">
						<td><label>Advertiser</label></td>
						<td><select id="advertiser" name="advertiser">
								<option>Choose An Advertiser</option>
								<?php
									if(isset($this->data))
										foreach($this->data as $value)
											if($value["type"] == "Advertiser")
												echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
								?>
								</select></td>
						</tr>	
						<tr class="options">
							<td><label>Ad Network</label></td>
							<td><select id="network" name="network">
								<option>Choose A Network</option>
								<?php
									if(isset($this->data))
										foreach($this->data as $value)
											if($value["type"] == "Ad Network")
												echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
								?>
						</select></td>
					 </tr>		
					<tr class="options">
						<td><label>Offers</label></td>
						<td><select id="offers" name="offers">
							<option>Choose A Offer</option>
						<?php
							if(isset($this->data))
								foreach($this->data as $value)
									if($value["type"] == "Offers")
										echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
						?>
						</select></td>
					</tr>
		
					<tr class="options">
						<td><label>Domains</label></td>
						<td><select id="domains"  name="domains">
								<option>Choose A Domain</option>
								<?php
									if(isset($this->data))
										foreach($this->data as $value)
											if($value["type"] == "Domains")
												echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
								?>
							</select></td>
					</tr>
		
				<tr class="options">
					<td><label>Cluster</label></td>
					<td><select id="cluster" name="cluster">
						<option>Choose A Cluster</option>
							<?php
									if(isset($this->data))
										foreach($this->data as $value)
											if($value["type"] == "Cluster")
												echo '<option value="'.$value["value"].'">'.$value["value"].'</option>';										
								?>
					</select></td>
				</tr>	
				<tr>
					<td></td>
					<td><input id="createCreative" type="submit" value="Create Creative"/></td>
				</tr>
			</form>
		</table>
	</div>
<div id="listCreatives">
	<ul>
		<?php
			foreach($this->camp as $value)
				echo "<li><a href='".realpath."campagin/updating?cid=".$value["id"]."' style='color:blue' >".$value["cluster"]."---".$value["id"]." ".$value["campaignName"]." ".$value['date'].' '.$value['domains']."</a></li>";
		?>
	</ul>
</div>	
</div>

</div>
</body>
</html>
