<?php
echo '<table width="600px" border="1" style="margin-left:100px;" align="center">';
foreach($this->data as $value)
{
	echo '<tr align="center">
		<td bgcolor="E0ffff" style="font-size:14px; font-weight:bold;">Campagin Name</td>
		<td>'.$value["campaignName"].'</td>
	</tr>
	<tr align="center">
		<td bgcolor="E0ffff" style="font-size:14px; font-weight:bold;">Advertiser</td>
		<td>'.$value["advertiser"].'</td>
	</tr>
	<tr align="center">
		<td bgcolor="E0ffff" style="font-size:14px; font-weight:bold;">Network</td>
		<td>'.$value["network"].'</td>
	</tr>
	<tr align="center">
		<td bgcolor="E0ffff" style="font-size:14px; font-weight:bold;">Domains</td>
		<td>'.$value["domains"].'</td>
	</tr>
	<tr align="center">
		<td bgcolor="E0ffff" style="font-size:14px; font-weight:bold;">Cluster</td>
		<td>'.$value["cluster"].'</td>
	</tr>
	<tr align="center">
		<td bgcolor="E0ffff" style="font-size:14px; font-weight:bold;">Offers</td>
		<td>'.$value["offers"].'</td>
	</tr>
	<tr align="center">
		<td bgcolor="E0ffff" style="font-size:14px; font-weight:bold;">Date</td>
		<td>'.$value["date"].'</td>
	</tr>';
}
echo '</table>';

foreach($this->create as $value)
{
	echo '<br /><a style="margin-left:100px;" href="" />'.$value["name"].'</a> <br />';
}

echo '<form style="margin-left:100px;"  method="post" action="'.realpath.'campagin/updating?action=addlink&cid='.$value["campagin_id"].'"">
						<input type="hidden" name="campagin_id" value="'.$value["id"].'" />  <br />
						<input type="text" name="name" /><input type="submit" value="Add Creative" />
					</form>';

